Repository HYF-Class20/Sound-Blog-Platform, pull requests merged in 2023-12, with the labels that each got.

#53 updating root component
  src/App.jsx
Labels: component

#56 update files
  README.md
  index.html
  src/App.jsx
  src/components/AudioPlayer/AudioPlayer.css
  src/components/Category/Category.css
  src/components/Category/Category.jsx
  src/components/NavigationBar/NavigationBar.css
  src/components/SoundList/SoundList.css
  src/components/SoundList/SoundList.jsx
Labels: bug

#61 general styling fixes and scroll functionality
  src/components/Category/Box.css
  src/components/Category/Category.css
  src/components/NavigationBar/NavigationBar.css
  src/components/NavigationBar/NavigationBar.jsx
  src/components/SoundList/SoundList.css
  src/components/SoundList/SoundList.jsx
  src/components/searchBar/SearchBar.css
Labels: enhancement

#59 update readme file
  README.md
  src/assets/screenshot.png
Labels: documentation

#62 fixing sound logo image path
  src/App.jsx
  src/components/AudioPlayer/AudioPlayer.jsx
Labels: bug

#65 change fetching server
  src/App.jsx
Labels: enhancement

#66 https fix
  index.html
Labels: bug
