Repository HYF-Class20/Sound-Blog-Platform, pull requests merged in 2023-11, with the labels that each got.

#7 adding the user personas file
  planning/user-personas.md
Labels: documentation

#14 Backlog
  planning/backlog.md
Labels: documentation

#19 Add wireframe file
  planning/wireframe.png
Labels: documentation, wireframe

#17 UpdateReadmeFile
  README.md
  assets/logo.png
Labels: documentation

#23 change logo path name in readme file
  README.md
Labels: documentation

#28 adding communication file
  planning/communication.md
Labels: documentation

#39 adding player component first version
  package.json
  src/components/player/player.css
  src/components/player/player.jsx
  src/components/player/render-player.css
  src/components/player/render-player.jsx
Labels: component

#37 update constraints with accurate info
  planning/constraints.md
Labels: documentation

#38 updating 4th week progress
  planning/communication.md
Labels: documentation

#36 addedNavigationBar
  Component/Category/Box.css
  Component/Category/Box.jsx
  Component/Category/Category.css
  package-lock.json
  package.json
  src/App.css
  src/App.jsx
  src/assets/sound_logo.png
  src/components/NavigationBar/NavigationBar.css
  src/components/NavigationBar/NavigationBar.jsx
  src/fonts/Montserrat-Medium.ttf
  src/index.css
Labels: enhancement
